import { createAccountServer } from './accounts.mjs';
import { loadApiEnvironment } from './environment.mjs';
loadApiEnvironment();
if (!process.env.MONGODB_URI) throw new Error('Set MONGODB_URI in .env before starting the account API.');
if (process.env.RENDER === 'true' && (!process.env.RESEND_API_KEY || !process.env.RESEND_FROM || !process.env.OTP_SECRET || process.env.OTP_SECRET.length < 32)) throw new Error('Configure RESEND_API_KEY, RESEND_FROM, and a strong OTP_SECRET on Render.');
const port = Number(process.env.PORT || process.env.API_PORT || 3001);
const host = process.env.API_HOST || (process.env.RENDER === 'true' ? '0.0.0.0' : '127.0.0.1');
if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error('PORT must be a valid TCP port.');
const server = createAccountServer();
server.listen(port, host, () => console.log(`Account API listening on http://${host}:${port}`));
for (const signal of ['SIGINT', 'SIGTERM']) process.once(signal, () => server.close(async () => { await server.closeDatabase(); process.exit(0); }));
