import { useEffect, useRef, useState } from 'react';
import { BrowserRouter, Link, Route, Routes, useLocation, useParams } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Check, CalendarDays, MapPin, Phone, Mail, Clock, ChevronDown, GraduationCap, HeartHandshake } from 'lucide-react';
import { Button, ContactCTA, Footer, Header, Icon, PageHeading, ProgramGrid } from './components';
import { academyContact, faqs, generalRequirements, programs, services } from './data';
import MotionEffects from './MotionEffects';
import { AccountForm, Dashboard } from './StudentAccount';
import './accounts.css';
import { ClassSchedule, NewsSection, ResourceDirectory, SocialLinks, StudentExperiences } from './ContentSections';
const metadata = {
  '/register': ['Create an Account', 'Create your CNA Training Academy student account.'],
  '/login': ['Student Sign In', 'Sign in to your CNA Training Academy student account.'],
  '/dashboard': ['Student Dashboard', 'Your personal CNA Training Academy student dashboard.'],
  '/': ['Healthcare Training in Bethany, OK', 'Explore CNA, HHA, CMA, and advanced medication aide training at CNA Training Academy in Bethany, Oklahoma.'],
  '/programs': ['Healthcare Training Programs', 'Find nurse aide, home health aide, medication aide, and advanced training programs at CNA Training Academy.'],
  '/about': ['About Our Academy', 'Learn about CNA Training Academy’s practical healthcare education and supportive learning environment in Bethany, Oklahoma.'],
  '/admissions': ['Admissions & Enrollment', 'Review program eligibility, admission requirements, and registration steps for CNA Training Academy.'],
  '/contact': ['Contact & Directions', 'Contact CNA Training Academy at 7463 NW 23rd St., Bethany, OK 73008. Call (405) 315-1357 for admissions assistance.'],
  '/resources': ['Student & Academy Resources', 'Find application forms, student services, financial assistance, policies, calendars, news, and academy resources.'],
};
function RouteEffects() {
  const { pathname } = useLocation();
  const initial = useRef(true);
  useEffect(() => {
    const program = programs.find(p => pathname === `/programs/${p.slug}`);
    const [title, description] = program ? [program.name, program.description + ' Review eligibility and contact admissions in Bethany, Oklahoma.'] : metadata[pathname] || ['Page Not Found', 'Find programs, admissions information, and contact details for CNA Training Academy.'];
    document.title = `${title} | CNA Training Academy`;
    document.querySelector('meta[name="description"]').setAttribute('content', description);
    window.scrollTo({ top: 0, behavior: 'instant' });
    if (!initial.current) document.getElementById('main')?.focus({ preventScroll: true });
    initial.current = false;
  }, [pathname]);
  return null;
}
function FAQ() {
  return <section className="section faq-section"><div className="container faq-layout"><div><p className="eyebrow">A LITTLE CLARITY</p><h2>Good questions.<br />Helpful answers.</h2><p>Starting something new comes with questions. We’re here to help.</p><Link className="text-link" to="/contact">Talk with our team <ArrowUpRight size={18} aria-hidden="true" /></Link></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={18} aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></div></section>;
}
function Home() {
  return <>
    <section className="hero-section"><img className="hero-background" src="/images/healthcare-team.webp" alt="Healthcare professionals in blue scrubs smiling together" width="484" height="450" fetchPriority="high" /><div className="container hero-layout"><div className="hero-copy"><p className="eyebrow">HEALTHCARE TRAINING / BETHANY, OK</p><h1>CNA Training<br /><span>Academy.</span></h1><p className="hero-tagline">A career with purpose. A future in care.</p><div className="hero-bottom"><p className="hero-description">Explore our in-person healthcare classes in Bethany. Learn about programs, plan your visit, and create an account for your personal student dashboard.</p><div className="button-row"><Button to="/programs" variant="outline">Explore Programs</Button><Button to={services.apply}>Create account</Button></div></div></div><div className="hero-note"><HeartHandshake size={22} aria-hidden="true" /><span>People first.<br /><strong>Always.</strong></span></div></div></section>
    <div className="intro-strip"><div className="container strip-grid"><div><Icon type="care" /><span>Hands-on learning<strong>Skills for real patient care</strong></span></div><div><Icon type="support" /><span>Support along the way<strong>Guidance from your first step</strong></span></div><div><GraduationCap aria-hidden="true" /><span>A path for your goals<strong>Begin or build on your experience</strong></span></div></div></div>
    <section className="section programs-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">FIND YOUR PATH</p><h2>Small steps. Meaningful possibilities.</h2><p>Start a healthcare career or take your caregiving skills further.</p></div><Link className="text-link" to="/programs">View all programs <ArrowUpRight size={18} aria-hidden="true" /></Link></div><ProgramGrid /><ClassSchedule /></div></section>
    <section className="section learning-section"><div className="container learning-layout"><div className="learning-photo"><img src="/images/classroom.webp" width="768" height="512" loading="lazy" alt="Healthcare learners listening and taking notes in a classroom" /><span className="photo-label"><Icon type="book" size={19} /> LEARN IT. PRACTICE IT. BUILD CONFIDENCE.</span></div><div><p className="eyebrow">MORE THAN CLASSROOM LEARNING</p><h2>Skills in your hands.<br />Confidence in your care.</h2><p>Healthcare starts with people. Our training brings knowledge and practical learning together, so you can develop the skills to care with confidence.</p><div className="learning-point"><span>01</span><div><h3>Practice with purpose</h3><p>Build your understanding through classroom instruction, skills practice, and program-specific clinical learning.</p></div></div><div className="learning-point"><span>02</span><div><h3>Feel supported</h3><p>Learn in a supportive environment with professional guidance and personalized instruction.</p></div></div><div className="learning-point"><span>03</span><div><h3>Keep compassion at the center</h3><p>Develop a thoughtful approach to patient safety, dignity, and everyday care.</p></div></div><Button to="/about" variant="outline">Get to know our academy</Button></div></div></section>
    <section className="academy-intro section"><div className="container academy-layout"><div><p className="eyebrow">ROOTED IN BETHANY. FOCUSED ON YOU.</p><h2>A place to learn.<br />A purpose to grow.</h2></div><div><p>CNA Training Academy is a healthcare training school preparing compassionate, skilled, and confident caregivers. From nurse aide foundations to advanced medication aide skills, our focus is practical education and meaningful student support.</p><Link className="text-link" to="/about">Our academy, our approach <ArrowUpRight size={18} aria-hidden="true" /></Link></div></div></section>
    <StudentExperiences /><NewsSection /><FAQ /><section className="section resource-callout"><div className="container"><p className="eyebrow">YOUR ACADEMY CONNECTION</p><h2>Everything for your next step.</h2><div className="button-row"><Button to="/resources">Student & academy resources</Button><Button href={services.applicationForm} variant="outline">Application form</Button></div></div></section><ContactCTA />
  </>;
}
function Programs() {
  const [filter, setFilter] = useState('All programs');
  const options = ['All programs', 'Start your career', 'Advance your skills', 'Specialized training'];
  return <><PageHeading eyebrow="Programs" title="Find your next step in care." description="Whether you’re beginning a healthcare career or building on your experience, explore a program that fits your goals." /><section className="section"><div className="container"><div className="program-toolbar"><div className="filter-group" role="group" aria-label="Filter programs">{options.map(option => <button key={option} aria-pressed={filter === option} onClick={() => setFilter(option)}>{option}</button>)}</div><span aria-live="polite">{filter === 'All programs' ? '6' : programs.filter(p => p.category === filter).length} programs</span></div><ProgramGrid list={programs.filter(p => filter === 'All programs' || p.category === filter)} /><div className="notice"><CalendarDays aria-hidden="true" /><div><h3>Plan your training with admissions.</h3><p>Confirm current course lengths, training hours, tuition, and availability with our team before enrolling.</p><a href={services.calendar}>Open the course calendar <ArrowUpRight size={16} aria-hidden="true" /></a></div></div></div></section><ContactCTA /></>;
}
function CheckList({ items }) { return <ul className="check-list">{items.map(item => <li key={item}><Check size={17} aria-hidden="true" /><span>{item}</span></li>)}</ul>; }
function Resources() {
  return <><PageHeading eyebrow="Resources" title="Your academy, connected." description="Applications, student support, calendars, and the academy's official resources." /><section className="section"><div className="container"><ResourceDirectory /><ClassSchedule /></div></section><ContactCTA /></>;
}
function ProgramDetails() {
  const { slug } = useParams();
  const program = programs.find(p => p.slug === slug);
  if (!program) return <NotFound />;
  return <><PageHeading eyebrow="Programs" title={program.name} description={program.description}><span className="heading-tag">{program.category}</span></PageHeading><section className="section"><div className="container detail-layout"><div><Link className="text-link back-link" to="/programs">← All programs</Link><h2>Training with a purpose.</h2><p>{program.overview}</p><div className="detail-block"><h2>What you’ll learn</h2><CheckList items={program.learning} /></div><div className="detail-block"><h2>Entry requirements</h2><p>Eligibility varies by program. Review these requirements and confirm your individual eligibility with admissions.</p><CheckList items={program.requirements} /><h3>General admission & clinical requirements</h3><CheckList items={generalRequirements} /><p className="small-text">Admissions will confirm how clinical and health requirements apply to your program. Advanced program prerequisites must be complete before skills validation and testing.</p><Link className="text-link" to="/admissions">Full admissions information <ArrowRight size={17} aria-hidden="true" /></Link></div><div className="detail-block"><h2>Training format & scheduling</h2><p>Training is in person and instructor led. Contact admissions to confirm the course length, required hours, tuition, and current schedule. Clinical arrangements depend on your program.</p><Button href={services.calendar} variant="outline">Course Calendar</Button></div></div><aside className="enrollment-card"><span className="icon-tile"><Icon type={program.icon} size={30} /></span><h2>Your next step starts here.</h2><p>Have questions about this program? Our admissions team can help you plan.</p><Button href={services.apply}>Create account</Button><a className="enrollment-phone" href="tel:+14053151357"><Phone size={18} aria-hidden="true" /> (405) 315-1357</a><div className="aside-divider" /><span className="eyebrow">TRAINING LOCATION</span><p>7463 NW 23rd St.<br />Bethany, OK 73008</p><a className="text-link" href={services.directions}>Get directions <ArrowUpRight size={16} aria-hidden="true" /></a></aside></div></section><ContactCTA /></>;
}
function About() {
  return <><PageHeading eyebrow="About Us" title="Compassion is the beginning." description="We help you turn a desire to care into the knowledge, practical skills, and confidence to take your next step." /><section className="section"><div className="container learning-layout about-layout"><div className="about-photo"><img src="/images/care-team.webp" alt="Two caregivers pictured on the academy’s original website, one wearing teal scrubs and one holding charts" width="1024" height="564" loading="lazy" /><span>CARE STARTS WITH PEOPLE.</span></div><div><p className="eyebrow">CNA TRAINING ACADEMY</p><h2>Preparing caregivers.<br />Supporting possibility.</h2><p>Based in Bethany, Oklahoma, CNA Training Academy prepares compassionate, skilled, and confident caregivers through healthcare education.</p><p>Our mission is to equip students with the knowledge and practical skills to pursue work as Certified Nurse Aides, Home Health Aides, and Certified Medication Aides.</p><p>We believe students deserve access to quality education, professional guidance, and a supportive learning environment. Our instructors bring clinical experience and a passion for teaching to personalized, hands-on instruction.</p><Button to="/programs">Explore our programs</Button></div></div></section><section className="section soft-background"><div className="container"><p className="eyebrow">THE WAY WE LEARN</p><h2>Practical education. Personal attention.</h2><div className="values-grid">{[['book', 'Learn by doing', 'Classroom learning and practical skills training connect knowledge with everyday patient care.'], ['support', 'Grow with guidance', 'Individualized support and student services help learners navigate their training.'], ['care', 'Care with compassion', 'Confidence and technical skills grow alongside respect for the people you care for.']].map(([icon, title, text]) => <article key={title}><Icon type={icon} size={30} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><ContactCTA /></>;
}
function Admissions() {
  return <><PageHeading eyebrow="Admissions" title="Your healthcare journey starts here." description="A clear path from choosing your program to beginning your training. Our admissions team is here to help at every step." /><section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">HOW TO ENROLL</p><h2>Four steps toward your next chapter.</h2></div><Button href={services.apply}>Create account</Button></div><div className="steps-grid">{[['Choose & apply', 'Explore your program, create your student account, and contact admissions to arrange your application or an in-person visit.'], ['Prepare your documents', 'Coordinate required documents with admissions and complete applicable health and background requirements before clinicals.'], ['Confirm your tuition plan', 'Speak with admissions about current fees, payment, and any available payment-plan arrangements.'], ['Begin your training', 'Attend orientation and start your class after admissions confirms your enrollment and requirements.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="admissions-layout"><div><h2>Admission requirements</h2><p>Requirements below follow the academy’s dedicated admissions page. Eligibility and prerequisites vary by program.</p><CheckList items={generalRequirements} /><h3>Program eligibility</h3><div className="eligibility-list">{programs.map(program => <div key={program.slug}><Link to={`/programs/${program.slug}`}>{program.name}</Link><p>{program.requirements.slice(0, 2).join(' ')}</p></div>)}</div><p className="small-text">Complete all applicable health and background requirements before clinical rotations. Contact admissions for a review of your eligibility and required documents.</p></div><aside className="admissions-aside"><CalendarDays size={30} aria-hidden="true" /><h3>Make a plan that works for you.</h3><p>Review the live calendar and speak with admissions to confirm your program’s dates, duration, tuition, and payment options.</p><Button href={services.calendar} variant="outline">Course Calendar</Button><Button to="/contact">Contact admissions</Button><div className="document-note"><h3>Keep your information secure.</h3><p>Arrange document submission directly with admissions through academy-approved channels. This website does not collect identity documents, health records, or payment details.</p></div></aside></div></div></section><ContactCTA /></>;
}
function Contact() {
  return <>
    <PageHeading eyebrow="Contact" title="Let's talk about your future." description="Questions about a program, enrollment, or your next step? Connect with our team. We're happy to help." />
    <section className="section"><div className="container contact-layout"><div>
      <p className="eyebrow">WE'RE HERE TO HELP</p><h2>A conversation is a great place to start.</h2>
      <p>Call or email admissions for current program details, tuition, payment options, and enrollment guidance.</p>
      <div className="contact-method"><span className="icon-tile"><Phone aria-hidden="true" /></span><div><h3>Call our team</h3><p>Office <a href={academyContact.officeHref}>{academyContact.office}</a></p><p>Work <a href={academyContact.workHref}>{academyContact.work}</a></p><p>Fax <span>{academyContact.fax}</span></p></div></div>
      <div className="contact-method"><span className="icon-tile"><Mail aria-hidden="true" /></span><div><h3>Send an email</h3>{academyContact.emails.map(email => <a key={email} href={`mailto:${email}`}>{email}</a>)}</div></div>
      <div className="contact-method"><span className="icon-tile"><Clock aria-hidden="true" /></span><div><h3>Published office hours</h3><p><strong>{academyContact.officeHours}</strong></p><p className="small-text">Please call ahead to arrange assistance; availability may vary with classes and clinicals.</p></div></div>
      <div className="contact-message"><h3>Send a message</h3><Button href={services.inquiry} variant="outline">Academy inquiry form</Button><SocialLinks /></div>
    </div><aside><div className="visit-card"><div className="visit-graphic" aria-hidden="true"><div className="map-street street-one" /><div className="map-street street-two" /><div className="map-street street-three" /><MapPin size={45} /><span>BETHANY, OKLAHOMA</span></div><div className="visit-content"><p className="eyebrow">COME SAY HELLO</p><h2>Visit the academy.</h2><address>CNA Training Academy<br />{academyContact.address}</address><Button href={services.directions}>Get Directions</Button></div></div><ClassSchedule /></aside></div></section><ContactCTA />
  </>;
}
function NotFound() {
  return <section className="section not-found container"><span className="eyebrow">404 · PAGE NOT FOUND</span><h1>Let’s get you back<br />on the right path.</h1><p>The page you’re looking for may have moved. Explore our programs or contact the academy for help.</p><div className="button-row"><Button to="/">Back to Home</Button><Button to="/programs" variant="outline">Explore Programs</Button></div></section>;
}
export default function App() {
  return <BrowserRouter><RouteEffects /><MotionEffects /><Header /><main id="main" tabIndex={-1}><Routes><Route path="/" element={<Home />} /><Route path="/programs" element={<Programs />} /><Route path="/programs/:slug" element={<ProgramDetails />} /><Route path="/about" element={<About />} /><Route path="/admissions" element={<Admissions />} /><Route path="/contact" element={<Contact />} /><Route path="/resources" element={<Resources />} /><Route path="/register" element={<AccountForm register />} /><Route path="/login" element={<AccountForm />} /><Route path="/dashboard" element={<Dashboard />} /><Route path="*" element={<NotFound />} /></Routes></main><Footer /></BrowserRouter>;
}


